#!/bin/bash
echo "Copying files ..."
date
mkdir -p ../html/jquery
cp -Rf node_modules/jquery/dist ../html/public/jquery
#cp -Rf public/* ../html/public/
cp -f public/* ../html/public/
cp -Rf public/jquery ../html/public/
