name: nightly
on: 
  push :
    branches:
      - github-actions
jobs:
  setup-containers:
    strategy:
      matrix:
         os: [ 'el8' ]
      
    runs-on: ubuntu-latest
   
    container: 
      image: ghcr.io/perfsonar/docker-oneshot-builder/${{ matrix.os }}:latest
      volumes:
        - .:/build
    steps:
       - name: Check out Repo
         uses: actions/checkout@v3
 
